---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: toolbox
  user: ubuntu
  become: True
  gather_facts: True

  # This is what I'm using on my minimal web & mail server
  roles:
    - common
    - sslletsencrypt
    - jitsi
    - openslides

  # These are all roles in one
  #roles:
  #  - common
  #  - blog
  #  - mailserver
  #  - webmail
  #  - news
  #  - nextcloud
  #  - gitea
  #  - ircbouncer
  #  - xmpp
  #  - matrix
  #  - mastodon
  #  - iot
  #  - vpn
  #  - monitoring  # Monitoring role should be last. See roles/monitoring/README.md
