# must match values in roles/common
db_admin_username: 'postgres'
db_admin_password: "{{ lookup('password', secret + '/' + 'db_admin_password length=32') }}"

mail_db_username: 'mailuser'
mail_db_password: "{{ lookup('password', secret + '/' + 'mail_db_password length=32') }}"
mail_db_database: 'mailserver'

mail_server_subdomain: "mail"
mail_server_hostname: "{{ mail_server_subdomain }}.{{ domain }}"
mail_server_autoconfig_hostname: "autoconfig.{{ domain }}"
mail_header_privacy: 1

friendly_networks:
  - ""

virtual_domains:
  - name: "{{ domain }}"
    doc_root: "/var/www/{{ domain }}"

mail_virtual_users:
  - account: "{{ main_user_name }}"
    domain: "{{ domain }}"
    password: "{{ lookup('password', secret + '/' + 'mail_main_user_password length=20') | doveadm_pw_hash }}"
    sendonly: 0
  - account: "noreply"
    domain: "{{ domain }}"
    password: "{{ lookup('password', secret + '/' + 'mail_noreply_password length=20 chars=ascii_lowercase,ascii_uppercase,digits') | doveadm_pw_hash }}"
    sendonly: 1

mail_virtual_aliases:
  - source: "root@{{ domain }}"
    destination: "{{ admin_email }}"
  - source: "postmaster@{{ domain }}"
    destination: "{{ admin_email }}"
  - source: "webmaster@{{ domain }}"
    destination: "{{ admin_email }}"
  - source: "abuse@{{ domain }}"
    destination: "{{ admin_email }}"

zpush_timezone: "{{ common_timezone | default('Etc/UTC') }}"
