jitsi_subdomain: "jitsi"
jitsi_domain: "{{ jitsi_subdomain }}.{{ domain }}"

jitsi_accounts:
  - name: "{{ main_user_name }}"
    password: "{{ lookup('password', secret + '/' + 'jitsi_main_user_password length=32') }}"
