mastodon_subdomain: "social"
mastodon_domain: "{{ mastodon_subdomain }}.{{ domain }}"

ruby_version: 2.6.0
rbenv_version: v1.1.1
ruby_build_version: v20181225

mastodon_db_username: mastodonuser
mastodon_db_password: "{{ lookup('password', secret + '/' + 'mastodon_db_password length=32') }}"
mastodon_db_database: mastodon

mastodon_secret_key_base: "{{ lookup('password', secret + '/' + 'mastodon_secret_key_base length=128 chars=hexdigits') }}"
mastodon_otp_secret: "{{ lookup('password', secret + '/' + 'mastodon_otp_secret length=128 chars=hexdigits') }}"

# must match values in roles/common
db_admin_username: 'postgres'
db_admin_password: "{{ lookup('password', secret + '/' + 'db_admin_password length=32') }}"
