selfoss_subdomain: "news"
selfoss_domain: "{{ selfoss_subdomain }}.{{ domain }}"

selfoss_db_username: selfoss
selfoss_db_password: "{{ lookup('password', secret + '/' + 'selfoss_db_password length=32') }}"
selfoss_db_database: selfoss

selfoss_version: 2.18

selfoss_username: "{{ main_user_name }}"
# this is the sha512 hash of the desired password
selfoss_password_hash: "{{ lookup('password', secret + '/' + 'selfoss_password_hash length=32') | hash('sha512') }}"

# must match values in roles/common
db_admin_username: 'postgres'
db_admin_password: "{{ lookup('password', secret + '/' + 'db_admin_password length=32') }}"
